SELECT *
FROM CUSTOMERS ;

SELECT Name , Email
FROM CUSTOMERS ;

SELECT *
FROM ORDERS
WHERE Total_Amount > 150 ;

SELECT * 
FROM EMPLOYEES
WHERE Salary > 4000 ;

SELECT *
FROM ORDERS
ORDER BY Total_Amount ;

SELECT *
FROM CUSTOMERS
WHERE Name LIKE 'M%' ;

SELECT *
FROM CUSTOMERS
WHERE Email lIKE '%mail%' ;

SELECT *
FROM ORDERS
WHERE Total_Amount BETWEEN 150 AND 200 ;

SELECT *
FROM CUSTOMERS 
WHERE Customer_ID IN (1,3,5) ;

SELECT *
FROM EMPLOYEES
WHERE Superviser_ID IS NULL ;

SELECT Fname+' '+Lname [Full_Name]
FROM EMPLOYEES

SELECT *
FROM CUSTOMERS
WHERE Email IS NOT NULL ;

SELECT COUNT(Customer_ID) AS Total_Customer
FROM CUSTOMERS ;

SELECT *
FROM ORDERS
WHERE Total_Amount = (SELECT MAX(Total_Amount)  FROM ORDERS )

SELECT *
FROM ORDERS
WHERE Total_Amount = (SELECT MAX(Total_Amount) FROM ORDERS )

SELECT E.Fname , E.Lname , COUNT(Order_ID) AS Total_Order 
FROM EMPLOYEES E INNER JOIN ORDERS O
ON E.EMP_ID = O.EMP_ID
GROUP BY E.Fname , E.Lname

SELECT SUM(Total_Amount) AS Total_Sales
FROM ORDERS

SELECT AVG(Total_Amount) AS AVG_Total_Sales
FROM ORDERS

SELECT E.Fname , E.Lname , COUNT(Order_ID) AS Total_Order 
FROM EMPLOYEES E INNER JOIN ORDERS O
ON E.EMP_ID = O.EMP_ID
GROUP BY E.Fname , E.Lname
HAVING COUNT(Order_ID) > 1

SELECT C.Name , O.*
FROM CUSTOMERS C RIGHT JOIN ORDERS O
ON C.Customer_ID = O.Customer_ID

SELECT C.Name , E.Fname , O.Total_Amount
FROM CUSTOMERS C JOIN ORDERS O
ON C.Customer_ID = O.Customer_ID
JOIN EMPLOYEES E
ON O.EMP_ID = E.EMP_ID
